[tool.black]
# Black formatter configuration for ROS2 Workspace

# Line length to match flake8 and pylint
line-length = 88

# Target Python versions
target-version = ['py38', 'py39', 'py310', 'py311']

# Include file patterns
include = '\.pyi?$'

# Exclude patterns (build artifacts, caches, etc.)
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.pytest_cache
  | _build
  | buck-out
  | build
  | install
  | log
  | dist
  | .*\.egg-info
)/
'''

# Skip string normalization (preserve quotes)
skip-string-normalization = false

# Skip magic trailing comma
skip-magic-trailing-comma = false

# Preview mode for new features
preview = false

[tool.isort]
# Import sorting configuration for ROS2 Workspace

# Profile compatibility with black
profile = "black"

# Line length to match black and flake8
line_length = 88

# Multi-line output mode (hanging indent)
multi_line_output = 3

# Include trailing commas
include_trailing_comma = true

# Force grid wrap when imports are too long
force_grid_wrap = 0

# Use parentheses for line continuation
use_parentheses = true

# Ensure newline before comments
ensure_newline_before_comments = true

# Known third-party libraries (ROS2 and common Python packages)
known_third_party = [
    "rclpy", 
    "geometry_msgs", 
    "std_msgs", 
    "sensor_msgs",
    "nav_msgs",
    "tf2_ros",
    "tf2_geometry_msgs",
    "numpy", 
    "yaml",
    "pytest",
    "scipy",
    "matplotlib"
]

# Known first-party libraries (your workspace packages)
known_first_party = ["custom_interface", "ros2_traj_pkg"]

# Section order
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

# Skip files and directories
skip = ["build", "install", "log", "__pycache__"]

# Skip glob patterns
skip_glob = ["**/build/**", "**/install/**", "**/log/**", "**/__pycache__/**"]

# Force imports to be sorted within their section
force_sort_within_sections = true

# Combine star imports
combine_star = true

[tool.mypy]
# MyPy type checking configuration for ROS2 Workspace

# Python version to target (updated for compatibility)
python_version = "3.10"

# Basic type checking settings
warn_return_any = false
warn_unused_configs = true
warn_unreachable = true
warn_redundant_casts = true
warn_unused_ignores = false

# Error handling
ignore_missing_imports = true
follow_imports = "silent"
strict_optional = false
check_untyped_defs = false

# Output configuration
show_error_codes = true
show_column_numbers = true
show_error_context = true
color_output = true

# Cache configuration
cache_dir = ".mypy_cache"

# Exclude patterns
exclude = [
    "build/",
    "install/", 
    "log/",
    "__pycache__/",
    "test/"
]

# Per-module options for ROS2 packages
[[tool.mypy.overrides]]
module = [
    "rclpy.*",
    "geometry_msgs.*",
    "std_msgs.*",
    "sensor_msgs.*",
    "nav_msgs.*",
    "tf2_ros.*",
    "tf2_geometry_msgs.*",
    "custom_interface.*"
]
ignore_missing_imports = true
