name: ROS2_CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    container:
      image: ros:humble

    steps:
      - name: Checkout code from repo
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y \
            python3-colcon-common-extensions \
            python3-pip \
            python3-flake8 \
            python3-pytest

      - name: Install Python dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Install ROS dependencies
        run: |
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build
          source .install/setup.bash

      - name: Run tests
        run: |
          source /opt/ros/humble/setup.bash
          source install/setup.bash
          colcon test --packages-select custom_interface ros2_traj_pkg \
            --event-handlers console_direct+
          colcon test-result --verbose

      - name: Run linting
        run: |
          chmod +x run_linting.sh
          source /opt/ros/humble/setup.bash
          source .install/setup.bash
          ./run_linting.sh
      
      